
package com.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2016-05-19T17:08:42.734+03:00
 * Generated source version: 2.4.0
 * 
 */
public final class Soapresponder_SoapresponderSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://soapclient.com/xml/soapresponder.wsdl", "soapresponder");

    private Soapresponder_SoapresponderSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Soapresponder_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Soapresponder_Service ss = new Soapresponder_Service(wsdlURL, SERVICE_NAME);
        Soapresponder port = ss.getSoapresponderSOAP();  
        
        {
        System.out.println("Invoking newOperation...");
        java.lang.String _newOperation_in = "_newOperation_ın962353598";
        java.lang.String _newOperation__return = port.newOperation(_newOperation_in);
        System.out.println("newOperation.result=" + _newOperation__return);


        }

        System.exit(0);
    }

}
