
/*
 * 
 */

package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2016-05-19T17:08:42.939+03:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "soapresponder", 
                  wsdlLocation = "file:/D:/YazilimDEPO/eclipse/workspace-eclipse/Q8_WebService/soapresponder.wsdl",
                  targetNamespace = "http://soapclient.com/xml/soapresponder.wsdl") 
public class Soapresponder_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soapclient.com/xml/soapresponder.wsdl", "soapresponder");
    public final static QName SoapresponderSOAP = new QName("http://soapclient.com/xml/soapresponder.wsdl", "soapresponderSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/YazilimDEPO/eclipse/workspace-eclipse/Q8_WebService/soapresponder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Soapresponder_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/YazilimDEPO/eclipse/workspace-eclipse/Q8_WebService/soapresponder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Soapresponder_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Soapresponder_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Soapresponder_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Soapresponder_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Soapresponder_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Soapresponder_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Soapresponder
     */
    @WebEndpoint(name = "soapresponderSOAP")
    public Soapresponder getSoapresponderSOAP() {
        return super.getPort(SoapresponderSOAP, Soapresponder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soapresponder
     */
    @WebEndpoint(name = "soapresponderSOAP")
    public Soapresponder getSoapresponderSOAP(WebServiceFeature... features) {
        return super.getPort(SoapresponderSOAP, Soapresponder.class, features);
    }

}
